const CiudadesData = [{
        'Colombia': [
            'Arauca',
            'Armenia',
            'Barranquilla',
            'Bogotá',
            'Bucaramanga',
            'Cali',
            'Cartagena de Indias',
            'Cúcuta',
            'Florencia',
            'Ibagué',
            'Inírida',
            'Manizales',
            'Medellín',
            'Mitú',
            'Mocoa',
            'Montería',
            'Neiva',
            'Pasto',
            'Pereira',
            'Popayán',
            'Puerto Carreño',
            'Quibdó',
            'Riohacha',
            'San Andrés',
            'San José del Guaviare',
            'Santa Marta',
            'Sincelejo',
            'Tunja',
            'Valledupar',
            'Villavicencio',
            'Yopal',
            'Leticia'
        ],
        'Mexico': [
            'Abasolo',
            'Abasolo',
            'Acajete',
            'Acajete',
            'Acala',
            'Acambay',
            'Acanceh',
            'Acapetlahuaya',
            'Acaponeta',
            'Acapulco de Juárez',
            'Acatlán',
            'Acatzingo',
            'Acaxochitlán',
            'Acaxtlahuacán de Albino Zertuche',
            'Acayucan',
            'Acolman',
            'Aconchi',
            'Acteopan',
            'Acuamanala',
            'Acuítzio del Canje',
            'Agua Dulce',
            'Agua Prieta',
            'Aguascalientes',
            'Aguililla',
            'Ahuacatlán',
            'Ahuatlán',
            'Ahuazotepec',
            'Ahuehuetitlán',
            'Ajalpan',
            'Álamo',
            'Albarradas',
            'Aldama',
            'Allende',
            'Allende',
            'Almoloya',
            'Almoloya de Alquisiras',
            'Almoloya de Juárez',
            'Almoloya del Río',
            'Alpoyeca',
            'Altamirano',
            'Altar',
            'Altata',
            'Altepexi',
            'Altotonga',
            'Álvaro Obregón',
            'Amacueca',
            'Amacuzac',
            'Amanalco de Becerra',
            'Amatenango de la Frontera',
            'Amatenango del Valle',
            'Amatitán',
            'Amaxac de Guerrero',
            'Ameca',
            'Amecameca de Juárez',
            'Amozoc',
            'Angamacutiro de la Unión',
            'Animas Trujano',
            'Apan',
            'Apaseo el Alto',
            'Apaxco de Ocampo',
            'Apaxtla de Castrejón',
            'Apazapan',
            'Apetatitlán Antonio Carbajal',
            'Apizaco',
            'Apoala',
            'Aporo',
            'Apulco',
            'Aquila',
            'Aquixtla',
            'Arcelia',
            'Ario de Rosales',
            'Arroyo Seco',
            'Arteaga',
            'Ascensión',
            'Asunción Nochixtlán',
            'Asunción Ocotlán',
            'Asunción Tlacolulita',
            'Atarjea',
            'Atenco',
            'Atenguillo',
            'Atlacomulco de Fabela',
            'Atlatlahucan',
            'Atlautla',
            'Atlequizayan',
            'Atoyac de Álvarez',
            'Atoyatempan',
            'Atzacan',
            'Atzala',
            'Atzitzintla',
            'Autlán',
            'Autlán de Navarro',
            'Axapusco',
            'Axutla',
            'Ayahualulco',
            'Ayapango',
            'Ayoquezco de Aldama',
            'Ayotoxco de Guerrero',
            'Ayutla',
            'Ayutla de los Libres',
            'Baca',
            'Balancán',
            'Balancán',
            'Bejucal de Ocampo',
            'Benito Juárez',
            'Bochil',
            'Briseñas de Matamoros',
            'Buenavista de Cuéllar',
            'Bustamante',
            'Cabo San Lucas',
            'Cacahoatán',
            'Cadereyta',
            'Cajonos',
            'Calihualá',
            'Calimaya de Díaz González',
            'Calkiní',
            'Calotmul',
            'Calpulalpan',
            'Camarón de Tejeda',
            'Campeche',
            'Cananea',
            'Canatlán',
            'Cancún',
            'Candelaria Loxicha',
            'Cañitas de Felipe Pescador',
            'Capulhuac',
            'Cardenas',
            'Cárdenas',
            'Carmen',
            'Castillo de Teayo',
            'Caxhuacán',
            'Celaya',
            'Celestún',
            'Cenotillo',
            'Cerro de San Pedro',
            'Chalchihuitán',
            'Chalco',
            'Champotón',
            'Chamula',
            'Chanal',
            'Chapultepec',
            'Charcas',
            'Chavinda',
            'Chenalhó',
            'Cherán',
            'Chetumal',
            'Chiapilla',
            'Chiautla',
            'Chicahua',
            'Chichihualco',
            'Chicoloapan',
            'Chicomuselo',
            'Chiconcuac',
            'Chicxulub Pueblo',
            'Chietla',
            'Chigmecatitlán',
            'Chignahuapan',
            'Chihuahua',
            'Chila',
            'Chila de la Sal',
            'Chilcuautla',
            'Chilpancingo',
            'Chimalhuacán',
            'Chimaltitán',
            'China',
            'Chucándiro',
            'Chumatlán',
            'Churumuco de Morelos',
            'Ciénega de Flores',
            'Ciénega de Zimatlán',
            'city',
            'Ciudad Altamirano',
            'Ciudad Apodaca',
            'Ciudad Ayala',
            'Ciudad Camargo',
            'Ciudad Constitución',
            'Ciudad de Atlixco',
            'Ciudad de Huajuapam de León',
            'Ciudad de Huitzuco',
            'Ciudad del Carmen',
            'Ciudad Fernández',
            'Ciudad General Escobedo',
            'Ciudad Guzmán',
            'Ciudad Hidalgo',
            'Ciudad Hidalgo',
            'Ciudad Juárez',
            'Ciudad Lázaro Cárdenas',
            'Ciudad Madero',
            'Ciudad Mante',
            'Ciudad Manuel Doblado',
            'Ciudad Mendoza',
            'Ciudad Miguel Alemán',
            'Ciudad Nezahualcóyotl',
            'Ciudad Obregón',
            'Ciudad Valles',
            'Ciudad Victoria',
            'Coahuayutla de Guerrero',
            'Coalcomán de Vázquez Pallares',
            'Coatecas Altas',
            'Coatepec',
            'Coatepec Harinas',
            'Coatlán del Río',
            'Coatzacoalcos',
            'Coatzingo',
            'Coaxomulco',
            'Cocotitlán',
            'Coeneo de la Libertad',
            'Cohuecán',
            'Coixtlahuaca',
            'Colima',
            'Colipa',
            'Colonia Manuel Gonzalez',
            'Comapa',
            'Comitán de Domínguez',
            'Comonfort',
            'Compostela',
            'Concepción de Buenos Aires',
            'Conkal',
            'Constancia del Rosario',
            'Contepec',
            'Copándaro de Galeana',
            'Coquimatlán',
            'Córdoba',
            'Cosautlán de Carvajal',
            'Cosío',
            'Cosoltepec',
            'Cotija de la Paz',
            'Coxcatlán',
            'Coxquihui',
            'Coyotepec',
            'Coyutla',
            'Cualác',
            'Cuanalá',
            'Cuapiaxtla',
            'Cuapiaxtla de Madero',
            'Cuauhtémoc',
            'Cuauhtémoc',
            'Cuautempan',
            'Cuautepec',
            'Cuautepec de Hinojosa',
            'Cuautla',
            'Cuautlancingo',
            'Cuencamé',
            'Cuerámaro',
            'Cuernavaca',
            'Cuetzala del Progreso',
            'Cuetzalan',
            'Cuidad Sabinas Hidalgo',
            'Cuilapan de Guerrero',
            'Cuitzeo del Porvenir',
            'Culiacán',
            'Cunduacán',
            'Degollado',
            'Delicias',
            'Doctor Coss',
            'Doctor Mora',
            'Domingo Arenas',
            'Dos Ríos',
            'Durango',
            'Dzilam de Bravo',
            'Dzilam González',
            'Dzitás',
            'Ecatzingo',
            'Ejido Nautla',
            'Ejido Piedras Negras',
            'Ejutla de Crespo',
            'El Arenal',
            'El Dorado',
            'El Espinal',
            'El Fresno',
            'El Grullo',
            'El Guayabito',
            'El Higo',
            'El Limón',
            'El Oro',
            'El Oro de Hidalgo',
            'El Porvenir de Velasco Suárez',
            'El Salto',
            'Emiliano Zapata',
            'Emiliano Zapata',
            'Emiliano Zapata',
            'Emiliano Zapata',
            'Empalme',
            'Encarnación de Díaz',
            'Ensenada',
            'Epazoyucan',
            'Erongarícuaro',
            'Escuinapa de Hidalgo',
            'Escuintla',
            'Españita',
            'Esperanza',
            'Espinal',
            'Espita',
            'Estación Ojinaga',
            'Ezequiel Montes',
            'Felipe Carrillo Puerto',
            'Fortín de las Flores',
            'Frontera',
            'Frontera Hidalgo',
            'García',
            'Genaro Codina',
            'General Bravo',
            'General Zaragoza',
            'General Zuazua',
            'Gómez Farías',
            'Gomez Palacio',
            'Grajales',
            'Gran Morelos',
            'Guadalajara',
            'Guadalupe',
            'Guamúchil',
            'Guanajuato',
            'Guasavito',
            'Guerrero',
            'Guerrero Negro',
            'Halachó',
            'Hecelchakán',
            'Hermosillo',
            'Heroica Caborca',
            'Heroica Ciudad de Tlaxiaco',
            'Heroica Guaymas',
            'Heróica Zitácuaro',
            'Hidalgo',
            'Higueras',
            'Honey',
            'Hopelchén',
            'Huamantla',
            'Huandacareo',
            'Huaniqueo de Morales',
            'Huaquechula',
            'Huasca de Ocampo',
            'Huatabampo',
            'Huatlatlauca',
            'Huatusco de Chicuellar',
            'Huauchinango',
            'Huehuetla',
            'Huehuetla',
            'Huehuetoca',
            'Huejotzingo',
            'Huépac',
            'Huetamo de Núñez',
            'Hueyotlipan',
            'Hueyotlipan',
            'Hueypoxtla',
            'Hueytamalco',
            'Huiloapan',
            'Huiramba',
            'Huitzilan',
            'Huixcolotla',
            'Huixquilucan de Degollado',
            'Huixtán',
            'Hunucmá',
            'Iguala de la Independencia',
            'Indaparapeo',
            'Irapuato',
            'Irimbo',
            'Isla Mujeres',
            'Ixcamilpa',
            'Ixcapuzalco',
            'Ixcateopan de Cuauhtémoc',
            'Ixhuacán de los Reyes',
            'Ixhuatlán del Café',
            'Ixhuatlancillo',
            'Ixil',
            'Ixmiquilpan',
            'Ixpantepec Nieves',
            'Ixtacamaxtitlán',
            'Ixtacuixtla',
            'Ixtaczoquitlán',
            'Ixtapa',
            'Ixtapaluca',
            'Ixtapan de la Sal',
            'Ixtapan del Oro',
            'Ixtenco',
            'Ixtepec',
            'Ixtlahuaca',
            'Ixtlahuacán',
            'Ixtlán de los Hervores',
            'Ixtlán del Río',
            'Izamal',
            'Izúcar de Matamoros',
            'Jala',
            'Jalacingo',
            'Jalcomulco',
            'Jalpa',
            'Jalpa de Méndez',
            'Jalpan',
            'Jaltenco',
            'Jaltepetongo',
            'Jáltipan de Morelos',
            'Jamiltepec',
            'Jerécuaro',
            'Jiquílpan de Juárez',
            'Jiutepec',
            'Jocotitlán',
            'Jojutla',
            'Jonotla',
            'Jonuta',
            'Joquicingo de León Guzmán',
            'Juan Aldama',
            'Juchique de Ferrer',
            'Juchitán de Zaragoza',
            'Juchitepec',
            'Juchitlán',
            'Julimes',
            'Jungapeo de Juárez',
            'Kanasín',
            'La Barca',
            'La Concordia',
            'La Cruz',
            'La Huacana',
            'La Independencia',
            'La Manzanilla de la Paz',
            'La Paz',
            'La Pe',
            'La Perla',
            'La Piedad',
            'La Unión',
            'Lagos de Moreno',
            'Lagunillas',
            'Larráinzar',
            'Las Choapas',
            'Las Marías',
            'Las Minas',
            'Las Vigas de Ramírez',
            'León de los Aldama',
            'Lerma de Villada',
            'Libres',
            'Linares',
            'Loreto',
            'Los Herreras',
            'Los Mochis',
            'Los Ramones',
            'Los Reyes Acaquilpan',
            'Los Reyes de Juárez',
            'Luis Moya',
            'Macuspana',
            'Magdalena',
            'Magdalena',
            'Magdalena Jaltepec',
            'Magdalena Mixtepec',
            'Magdalena Teitipac',
            'Magdalena Tequisistlán',
            'Magdalena Yodocono de Porfirio Díaz',
            'Magdalena Zahuatlán',
            'Malinalco',
            'Maltrata',
            'Manzanillo',
            'Mapastepec',
            'Maravatío de Ocampo',
            'Mariano Escobedo',
            'Marín',
            'Martínez de la Torre',
            'Matamoros',
            'Matamoros',
            'Matehuala',
            'Maxcanú',
            'Mazamitla',
            'Mazapa',
            'Mazapiltepec',
            'Mazatán',
            'Mazatán',
            'Mazatecochco',
            'Mazatepec',
            'Mazatlán',
            'Meoqui',
            'Mérida',
            'Metapa',
            'Metepec',
            'Metepec',
            'Metlatónoc',
            'Mexicali',
            'Mexico City',
            'Mexticacán',
            'Miacatlán',
            'Miahuatlán',
            'Miahuatlán',
            'Miahuatlán de Porfirio Díaz',
            'Mier',
            'Miguel Ahumada',
            'Mina',
            'Minatitlan',
            'Mineral de Angangueo',
            'Mineral del Monte',
            'Misantla',
            'Mixistlán',
            'Mixtla',
            'Mixtlán',
            'Mococha',
            'Moctezuma',
            'Momax',
            'Monclova',
            'Montemorelos',
            'Monterrey',
            'Morelia',
            'Morelos',
            'Morelos',
            'Motozintla',
            'Motul',
            'Muñoz Arenas de Domingo',
            'Nacajuca',
            'Naco',
            'Nacozari Viejo',
            'Nahuatzén',
            'Nanacamilpa',
            'Nativitas',
            'Naupan',
            'Navojoa',
            'Nealtican',
            'Nezahualcóyotl',
            'Nieves',
            'Nochistlán de Mejía',
            'Nogales',
            'Nogales',
            'Nombre de Dios',
            'Nopaltepec',
            'Nopalucán',
            'Nueva Rosita',
            'Nuevo Casas Grandes',
            'Nuevo Laredo',
            'Nuevo Necaxa',
            'Nuevo San Juan Parangaricutiro',
            'Nuevo Urecho',
            'Numarán',
            'Oaxaca',
            'Ocampo',
            'Ocosingo',
            'Ocotlán de Morelos',
            'Ocoyoacac',
            'Ocuílan de Arteaga',
            'Ocuituco',
            'Ojuelos de Jalisco',
            'Oluta',
            'Ometepec',
            'Omitlán de Juárez',
            'Oquitoa',
            'Orizaba',
            'Ostuacán',
            'Otumba',
            'Otzoloapan',
            'Oxchuc',
            'Ozumba',
            'Pachuca',
            'Pahuatlán de Valle',
            'Pajacuarán',
            'Palenque',
            'Palo Alto',
            'Panabá',
            'Panindícuaro',
            'Panotla',
            'Pánuco',
            'Papalotla',
            'Papalotla',
            'Paraiso',
            'Parral',
            'Parras de la Fuente',
            'Pastor Ortíz',
            'Pátzcuaro',
            'Penjamillo de Degollado',
            'Pénjamo',
            'Peñamiller',
            'Perote',
            'Pesquería',
            'Petatlán',
            'Petlalcingo',
            'Peto',
            'Piedras Negras',
            'Pihuamo',
            'Pijijiapan',
            'Pilcaya',
            'Pinal de Amoles',
            'Pinos',
            'Pinotepa',
            'Pinotepa de Don Luis',
            'Pitiquito',
            'Pluma Hidalgo',
            'Poza Rica de Hidalgo',
            'Progreso',
            'Puebla',
            'Puente de Ixtla',
            'Puerto Escondido',
            'Puerto Vallarta',
            'Punta Prieta',
            'Puruándiro',
            'Putla Villa de Guerrero',
            'Quechultenango',
            'Queréndaro',
            'Querétaro',
            'Quimixtlán',
            'Quintana Roo',
            'Quiriego',
            'Quiroga',
            'Quitupán',
            'Rafael Delgado',
            'Rafael J. García',
            'Ramos Arizpe',
            'Rayón',
            'Rayones',
            'Reynosa',
            'Río Blanco',
            'Río Grande',
            'Ríoverde',
            'Rojas de Cuauhtémoc',
            'Romita',
            'Rosales',
            'Rosamorada',
            'Salamanca',
            'Salina Cruz',
            'Salinas Victoria',
            'Saltillo',
            'Saltillo',
            'Salto de Agua',
            'San Agustín Amatengo',
            'San Agustín Atenango',
            'San Agustín Chayuco',
            'San Agustín Yatareni',
            'San Andrés Calpan',
            'San Andrés Dinicuiti',
            'San Andrés Huaxpaltepec',
            'San Andrés Huayápam',
            'San Andrés Sinaxtla',
            'San Andrés Solaga',
            'San Andrés Tenejapan',
            'San Andrés Timilpan',
            'San Andrés Yaá',
            'San Antonino Castillo Velasco',
            'San Antonino Monteverde',
            'San Antonio',
            'San Antonio Cañada',
            'San Antonio la Isla',
            'San Baltazar Chichicapam',
            'San Baltazar Loxicha',
            'San Bartolo Coyotepec',
            'San Bartolo Morelos',
            'San Bartolo Tutotepec',
            'San Bartolo Yautepec',
            'San Bartolomé Loxícha',
            'San Bartolomé Quialana',
            'San Bernardino Contla',
            'San Bernardo Mixtepec',
            'San Blas',
            'San Blas Atempa',
            'San Carlos Yautepec',
            'San Ciro de Acosta',
            'San Cristóbal Amatlán',
            'San Cristóbal Amoltepec',
            'San Cristóbal de las Casas',
            'San Cristóbal Lachirioag',
            'San Diego de la Unión',
            'San Dionisio Ocotepec',
            'San Esteban Atatlahuca',
            'San Felipe',
            'San Felipe',
            'San Felipe de Jesús',
            'San Felipe del Progreso',
            'San Francisco Cajonos',
            'San Francisco Chindúa',
            'San Francisco Jaltepetongo',
            'San Francisco Lachigoló',
            'San Francisco Nuxaño',
            'San Francisco Sola',
            'San Francisco Telixtlahuaca',
            'San Gregorio Atzompa',
            'San Ignacio',
            'San Ildefonso Amatlán',
            'San Ildefonso Villa Alta',
            'San Jerónimo Coatlán',
            'San Jerónimo de Juárez',
            'San Jerónimo Silacayoapilla',
            'San Jerónimo Sosola',
            'San Jerónimo Taviche',
            'San Jerónimo Tlacochahuaya',
            'San Jerónimo Xayacatlán',
            'San Joaquín',
            'San Jorge Nuchita',
            'San José Acateno',
            'San José Ayuquila',
            'San José Chiapa',
            'San José Chiltepec',
            'San José de Gracia',
            'San José Estancia Grande',
            'San José Lachiguirí',
            'San José Villa de Allende',
            'San Juan',
            'San Juan Achiutla',
            'San Juan Atzompa',
            'San Juan Bautista Jayacatlán',
            'San Juan Cancuc',
            'San Juan Chilateca',
            'San Juan Colorado',
            'San Juan de los Lagos',
            'San Juan del Estado',
            'San Juan del Río',
            'San Juan Diuxi',
            'San Juan Epatlán',
            'San Juan Guelavía',
            'San Juan Ihualtepec',
            'San Juan Juquila Vijanos',
            'San Juán Lachigalla',
            'San Juan Mixtepec',
            'San Juan Mixtepec',
            'San Juan Ñumí',
            'San Juan Petlapa',
            'San Juan Quiotepec',
            'San Juan Sayultepec',
            'San Juan Tabaá',
            'San Juan Teitipac',
            'San Juan Xiutetelco',
            'San Juan Yaee',
            'San Juan Yatzona',
            'San Juanito de Escobedo',
            'San Julián',
            'San Lorenzo',
            'San Lorenzo',
            'San Lorenzo Albarradas',
            'San Lorenzo Chiautzingo',
            'San Lucas',
            'San Lucas Quiavini',
            'San Luis Acatlán',
            'San Luis Amatlán',
            'San Luis de la Paz',
            'San Luis Potosí',
            'San Marcos Arteaga',
            'San Martín de las Pirámides',
            'San Martín de los Canseco',
            'San Martín Huamelulpam',
            'San Martín Itunyoso',
            'San Martin Texmelucan de Labastida',
            'San Martín Tilcajete',
            'San Martín Xaltocan',
            'San Mateo Atenco',
            'San Mateo Cajonos',
            'San Mateo Etlatongo',
            'San Mateo Mexicaltzingo',
            'San Mateo Nejápam',
            'San Matias Tlalancaleca',
            'San Melchor Betaza',
            'San Miguel Achiutla',
            'San Miguel Aloápam',
            'San Miguel Coatlán',
            'San Miguel de Allende',
            'San Miguel de Papasquiaro',
            'San Miguel del Puerto',
            'San Miguel Ejutla',
            'San Miguel Huautla',
            'San Miguel Ixitlán',
            'San Miguel Mixtepec',
            'San Miguel Panixtlahuaca',
            'San Miguel Tecomatlán',
            'San Miguel Tenango',
            'San Miguel Tilquiapam',
            'San Miguel Tlacamama',
            'San Miguel Zinacantepec',
            'San Nicolás',
            'San Nicolás de los Ranchos',
            'San Pablo Coatlán',
            'San Pablo Cuatro Venados',
            'San Pablo de las Tunas',
            'San Pablo Huitzo',
            'San Pablo Huixtepec',
            'San Pablo Macuiltianguis',
            'San Pablo Villa de Mitla',
            'San Pedro Apóstol',
            'San Pedro Atoyac',
            'San Pedro Comitancillo',
            'San Pedro Coxcaltepec',
            'San Pedro de Las Colonias',
            'San Pedro Huamelula',
            'San Pedro Jicayán',
            'San Pedro Mártir Quiechapa',
            'San Pedro Mártir Yucuxaco',
            'San Pedro Mixtepec',
            'San Pedro Mixtepec',
            'San Pedro Piedra Gorda',
            'San Pedro Pochutla',
            'San Pedro Quiatoni',
            'San Pedro Taviche',
            'San Pedro Tidaá',
            'San Pedro Topiltepec',
            'San Pedro y San Pablo Tequistepec',
            'San Pedro Yólox',
            'San Raymundo Jalpam',
            'San Salvador',
            'San Salvador el Verde',
            'San Salvador Tzompantepec',
            'San Sebastián Abasolo',
            'San Sebastián Coatlán',
            'San Sebastián Nicananduta',
            'San Sebastian Teitipac',
            'San Simón Almolongas',
            'San Simón de Guerrero',
            'San Vicente Coatlán',
            'San Vicente Lachixío',
            'San Vicente Nuñu',
            'Sanctorum',
            'Santa Ana',
            'Santa Ana',
            'Santa Ana del Valle',
            'Santa Ana Maya',
            'Santa Ana Tlapacoyan',
            'Santa Ana Zegache',
            'Santa Bárbara',
            'Santa Catalina Quieri',
            'Santa Catarina',
            'Santa Catarina Cuixtla',
            'Santa Catarina Loxicha',
            'Santa Catarina Mechoacán',
            'Santa Catarina Minas',
            'Santa Catarina Quiané',
            'Santa Catarina Tayata',
            'Santa Catarina Tlaltempan',
            'Santa Clara del Cobre',
            'Santa Clara Huitziltepec',
            'Santa Cruz',
            'Santa Cruz Atizapán',
            'Santa Cruz de Bravo',
            'Santa Cruz Mixtepec',
            'Santa Cruz Nundaco',
            'Santa Cruz Papalutla',
            'Santa Cruz Tayata',
            'Santa Cruz Tlaxcala',
            'Santa Cruz Xitla',
            'Santa Eulalia',
            'Santa Gertrudis',
            'Santa Inés del Monte',
            'Santa Inés Yatzeche',
            'Santa Isabel',
            'Santa Isabel Cholula',
            'Santa Lucía Ocotlán',
            'Santa María Apazco',
            'Santa María Camotlán',
            'Santa María Chachoápam',
            'Santa María Colotepec',
            'Santa María Cortijo',
            'Santa María Coyotepec',
            'Santa María del Rosario',
            'Santa María del Tule',
            'Santa María Ecatepec',
            'Santa María Guelacé',
            'Santa María Huatulco',
            'Santa María Huazolotitlán',
            'Santa María Jacatepec',
            'Santa María Jalapa del Marqués',
            'Santa María Lachixío',
            'Santa María Mixtequilla',
            'Santa María Nduayaco',
            'Santa María Quiegolani',
            'Santa María Rayón',
            'Santa María Sola',
            'Santa María Temaxcalapa',
            'Santa María Tepantlali',
            'Santa María Tonameca',
            'Santa María Xadani',
            'Santa María Yavesía',
            'Santa María Yucuhiti',
            'Santa María Zoquitlán',
            'Santa Rita Tlahuapan',
            'Santa Rosalia',
            'Santiago',
            'Santiago Apostol',
            'Santiago Astata',
            'Santiago Atzitzihuacán',
            'Santiago Ayuquililla',
            'Santiago Cacaloxtepec',
            'Santiago Camotlán',
            'Santiago Chazumba',
            'Santiago Comaltepec',
            'Santiago Huajolotitlán',
            'Santiago Huauclilla',
            'Santiago Ixcuintla',
            'Santiago Lalopa',
            'Santiago Laxopa',
            'Santiago Llano Grande',
            'Santiago Matatlán',
            'Santiago Miltepec',
            'Santiago Nejapilla',
            'Santiago Nundíche',
            'Santiago Nuyoó',
            'Santiago Suchilquitongo',
            'Santiago Tangamandapio',
            'Santiago Tenango',
            'Santiago Tetepec',
            'Santiago Textitlán',
            'Santiago Tíanguistenco',
            'Santiago Tilantongo',
            'Santiago Tillo',
            'Santiago Tulantepec',
            'Santiago Tuxtla',
            'Santiago Yogana',
            'Santiago Yolomécatl',
            'Santiago Zoochila',
            'Santo Domingo de Morelos',
            'Santo Domingo Huehuetlán',
            'Santo Domingo Roayaga',
            'Santo Domingo Tehuantepec',
            'Santo Domingo Tepuxtepec',
            'Santo Domingo Tlatayapam',
            'Santo Domingo Tomaltepec',
            'Santo Domingo Tonalá',
            'Santo Domingo Yodohino',
            'Santo Tomás de los Plátanos',
            'Santo Tomás Jalieza',
            'Santo Tomás Ocotepec',
            'Santos Reyes Tepejillo',
            'Sayula',
            'Sayula de Alemán',
            'Sección Primera Santiago Tetla',
            'Senguio',
            'Sergio Butrón Casas',
            'Seyé',
            'Silacayoápam',
            'Silao',
            'Sinaloa de Leyva',
            'Singuilucan',
            'Sitio de Xitlapehua',
            'Sochiapa',
            'Socoltenango',
            'Soconusco',
            'Soledad Atzompa',
            'Soledad de Doblado',
            'Soledad de Graciano Sánchez',
            'Soltepec',
            'Sotuta',
            'Soyaló',
            'Soyaltepec',
            'Sucilá',
            'Sultepec de Pedro Ascencio de Alquisiras',
            'Susupuato de Guerrero',
            'Tacámbaro de Codallos',
            'Tamasopo',
            'Tamazola',
            'Tamazulapam',
            'Tamazunchale',
            'Tampico',
            'Tamuin',
            'Tanetze de Zaragoza',
            'Tanhuato de Guerrero',
            'Taniche',
            'Tapachula',
            'Tapalpa',
            'Tapeixtles',
            'Tarandacuao',
            'Tarímbaro',
            'Tataltepec de Valdés',
            'Tatatila',
            'Taxco de Alarcón',
            'Tecali',
            'Tecámac',
            'Tecamachalco',
            'Tecax',
            'Tecoanapa',
            'Tecolotlán',
            'Tecomán',
            'Técpan de Galeana',
            'Tecuala',
            'Tehuacán',
            'Tejupilco de Hidalgo',
            'Telchac Puerto',
            'Teloloapan',
            'Temamatla',
            'Temascalapa',
            'Temascalcingo de José María Velazco',
            'Temascaltepec de González',
            'Temixco',
            'Temoac',
            'Temoaya',
            'Tenabo',
            'Tenamaxtlán',
            'Tenampa',
            'Tenampulco',
            'Tenancingo',
            'Tenango de Arista',
            'Tenango de Doria',
            'Tenango del Aire',
            'Tenejapa',
            'Teocelo',
            'Teojomulco',
            'Teopantlán',
            'Teopisca',
            'Teotihuacán',
            'Teotitlán del Valle',
            'Tepalcatepec',
            'Tepatlaxco',
            'Tepatlaxco',
            'Tepeaca',
            'Tepeapulco',
            'Tepechitlán',
            'Tepecoacuilco de Trujano',
            'Tepemaxalco',
            'Tepeojuma',
            'Tepetitla',
            'Tepetlaoxtoc',
            'Tepetlapa',
            'Tepetlixpa',
            'Tepetzintla',
            'Tepeyahualco',
            'Tepeyanco',
            'Tepic',
            'Tepoztlán',
            'Tequila',
            'Tequisquiapan',
            'Tequixquiac',
            'Terrenate',
            'Tetecala',
            'Tetela de Ocampo',
            'Tetela del Volcán',
            'Tetipac',
            'Tetlatlahuca',
            'Texcaltitlán',
            'Texcalyacac',
            'Texcatitlán',
            'Texcoco',
            'Texistepec',
            'Texmelucan',
            'Teziutlan',
            'Tezoatlán de Segura y Luna',
            'Tezontepec',
            'Tezoyuca',
            'Tianguismanalco',
            'Ticul',
            'Tierra Blanca',
            'Tierra Colorada',
            'Tierra Nueva',
            'Tijuana',
            'Tilapa',
            'Timucuy',
            'Tingambato',
            'Tinum',
            'Tixpehual',
            'Tixtla de Guerrero',
            'Tizayuca',
            'Tizimín',
            'Tlachichilco',
            'Tlacolula de Matamoros',
            'Tlacolulan',
            'Tlacotepec de Mejía',
            'Tlacuilotepec',
            'Tlacuitapan',
            'Tlahuitoltepec',
            'Tlalixtac de Cabrera',
            'Tlalixtaquilla',
            'Tlalmanalco de Velázquez',
            'Tlalnepantla',
            'Tlalpujahua de Rayón',
            'Tlaltenango',
            'Tlaltetela',
            'Tlaltizapán',
            'Tlanalapa',
            'Tlanepantla',
            'Tlapa de Comonfort',
            'Tlapacoyan',
            'Tlapanalá',
            'Tlaquiltenango',
            'Tlaxcala',
            'Tlaxco',
            'Tlaxco',
            'Tlaxiaco',
            'Tlayacapan',
            'Tlilapan',
            'Tocatlán',
            'Tochimilco',
            'Tochtepec',
            'Tolcayuca',
            'Toluca',
            'Tonatico',
            'Tonaya',
            'Tonila',
            'Torreon',
            'Totatiche',
            'Totolac',
            'Totolapa',
            'Totolapan',
            'Totoltepec',
            'Totoltepec de Guerrero',
            'Totontepec Villa de Morelos',
            'Totutla',
            'Trincheras',
            'Trinidad Zaachila',
            'Tula',
            'Tulancingo',
            'Tulcingo de Valle',
            'Tumbiscatío de Ruiz',
            'Turicato',
            'Túxpam de Rodríguez Cano',
            'Tuxpan',
            'Tuxpan',
            'Tuxpilla',
            'Tuxtla',
            'Tuxtla Chico',
            'Tuzamapan',
            'Tuzantla',
            'Tzintzuntzán',
            'Tzitzio',
            'Ucú',
            'Unión de San Antonio',
            'Unión de Tula',
            'Uruapan',
            'Valladolid',
            'Valle de Allende',
            'Valle de Bravo',
            'Valle de Juárez',
            'Valle de Santiago',
            'Valle Nacional',
            'Valparaíso',
            'Venustiano Carranza',
            'Veracruz',
            'Vicente Guerrero',
            'Victoria',
            'Viesca',
            'Villa Aldama',
            'Villa Atltzayanca de Hidalgo',
            'Villa Comaltitlán',
            'Villa Cuauhtémoc Otzolotepec',
            'Villa de Álvarez',
            'Villa de Arriaga',
            'Villa de Guadalupe',
            'Villa de Reyes',
            'Villa de Zaachila',
            'Villa Díaz Ordaz',
            'Villa Donato Guerra',
            'Villa García',
            'Villa Guerrero',
            'Villa Guerrero',
            'Villa Hidalgo',
            'Villa Hidalgo',
            'Villa Jiménez',
            'Villa Talea de Castro',
            'Villa Unión',
            'Villa Unión',
            'Villa Unión',
            'Villa Victoria',
            'Villa Zaragoza',
            'Villahermosa',
            'Villamar',
            'Villanueva',
            'Vista Hermosa de Negrete',
            'Xagacía',
            'Xalapa',
            'Xalatlaco',
            'Xalisco',
            'Xaloztoc',
            'Xayacatlán de Bravo',
            'Xico',
            'Xicotlán',
            'Xochiltepec',
            'Xochitepec',
            'Xonacatlán',
            'Yaganiza',
            'Yagul',
            'Yalina',
            'Yatzachi',
            'Yauhquemehcan',
            'Yautepec de Zaragoza',
            'Yaxcabá',
            'Yaxe',
            'Yaxkukul',
            'Yecapixtla',
            'Yecuatla',
            'Yucuita',
            'Yucuyachi',
            'Yurécuaro',
            'Zacapala',
            'Zacapú',
            'Zacatecas',
            'Zacatepec',
            'Zacatlán',
            'Zacazonapan',
            'Zacualpan',
            'Zacualpan de Amilpas',
            'Zamora',
            'Zamora Pico de Oro',
            'Zapotitlán Palmas',
            'Zapotlán de Juárez',
            'Zaragoza',
            'Zautla',
            'Zempoala',
            'Zimatlán de Álvarez',
            'Zinacantán',
            'Zinacatepec',
            'Zináparo',
            'Zinapécuaro',
            'Zitlaltepec',
            'Zongozotla',
            'Zoogocho',
            'Zoquiopan',
            'Zoquitlán',
            'Zozocolco de Hidalgo',
            'Zumpahuacán',
            'Zumpango',
            'Zumpango de Ocampo',
            'Zumpango del Río'
        ],
        'Brazil': [
            'Abaetetuba',
            'Abunã',
            'Acaraú',
            'Açu',
            'Alagoinhas',
            'Alenquer',
            'Almenara',
            'Altamira',
            'Alvorada',
            'Amapá',
            'Americana',
            'Anápolis',
            'Andradina',
            'Apodi',
            'Apucarana',
            'Aquidauana',
            'Aracaju',
            'Aracati',
            'Araçatuba',
            'Araçuaí',
            'Araguaína',
            'Araguari',
            'Arapiraca',
            'Arapongas',
            'Araranguá',
            'Araxá',
            'Arcoverde',
            'Aripuanã',
            'Ariquemes',
            'Assis',
            'Avaré',
            'Bacabal',
            'Bagé',
            'Balsas',
            'Barbacena',
            'Barcelos',
            'Barra do Bugres',
            'Barra do Corda',
            'Barra do Garças',
            'Barra Mansa',
            'Barras',
            'Barreiras',
            'Barreirinho',
            'Barreiros',
            'Barretos',
            'Batatais',
            'Baturité',
            'Bauru',
            'Belém',
            'Belo Horizonte',
            'Bento Gonçalves',
            'Blumenau',
            'Boa Vista',
            'Bocaiúva',
            'Bom Jesus da Lapa',
            'Botucatu',
            'Bragança',
            'Bragança Paulista',
            'Brasília',
            'Breves',
            'Brumado',
            'Brusque',
            'Cabo Frio',
            'Caçador',
            'Cachoeira do Sul',
            'Cachoeiro de Itapemirim',
            'Caicó',
            'Camaquã',
            'Cametá',
            'Camocim',
            'Campina Grande',
            'Campinas',
            'Campo Belo',
            'Campo Grande',
            'Campo Maior',
            'Campo Mourão',
            'Campos',
            'Canavieiras',
            'Canela',
            'Canindé',
            'Canoas',
            'Canoinhas',
            'Capanema',
            'Capitão Poço',
            'Caracaraí',
            'Caratinga',
            'Caràzinho',
            'Carpina',
            'Caruaru',
            'Cascavel',
            'Castanhal',
            'Castro',
            'Catalão',
            'Catanduva',
            'Caxias',
            'Caxias do Sul',
            'Ceres',
            'Chapadinha',
            'Chapecó',
            'Coari',
            'Codó',
            'Colíder',
            'Colinas',
            'Conceição do Araguaia',
            'Concórdia',
            'Conselheiro Lafaiete',
            'Coroatá',
            'Corumbá',
            'Crateús',
            'Crato',
            'Crato',
            'Criciúma',
            'Cristalina',
            'Cruzeiro do Sul',
            'Cuiabá',
            'Curitiba',
            'Curvelo',
            'Diamantina',
            'Divinópolis',
            'Dourados',
            'Eirunepé',
            'Erechim',
            'Estância',
            'Feira de Santana',
            'Fernandópolis',
            'Floriano',
            'Florianópolis',
            'Fonte Boa',
            'Formiga',
            'Formosa',
            'Fortaleza',
            'Foz do Iguaçu',
            'Franca',
            'Frutal',
            'Garanhuns',
            'Garça',
            'Goiana',
            'Goianésia',
            'Goiânia',
            'Governador Valadares',
            'Grajaú',
            'Granja',
            'Guaíra',
            'Guajará-Mirim',
            'Guanambi',
            'Guanhães',
            'Guarapuava',
            'Guaratinguetá',
            'Guaxupé',
            'Gurupi',
            'Icó',
            'Iguape',
            'Iguatu',
            'Ijuí',
            'Ilhéus',
            'Imbituba',
            'Imperatriz',
            'Inhumas',
            'Ipatinga',
            'Iporá',
            'Ipu',
            'Irati',
            'Irecê',
            'Itaberaba',
            'Itaberaí',
            'Itabuna',
            'Itacoatiara',
            'Itaituba',
            'Itajaí',
            'Itamaraju',
            'Itambé',
            'Itanhaém',
            'Itapecuru Mirim',
            'Itapetinga',
            'Itapetininga',
            'Itapeva',
            'Itapipoca',
            'Itaúna',
            'Itu',
            'Ituiutaba',
            'Itumbiara',
            'Itupiranga',
            'Iturama',
            'Jaboatão',
            'Jabuticabal',
            'Jacareacanga',
            'Jaguaquara',
            'Jaguarão',
            'Janaúba',
            'Januária',
            'Jaraguá do Sul',
            'Jardim',
            'Jataí',
            'Jaú',
            'Jequié',
            'Ji-Paraná',
            'Joaçaba',
            'João Pessoa',
            'Joinvile',
            'Juazeiro',
            'Juazeiro do Norte',
            'Juiz de Fora',
            'Jundiaí',
            'Laguna',
            'Lajes',
            'Lapa',
            'Lavras',
            'Leopoldina',
            'Limeira',
            'Linhares',
            'Londrina',
            'Macaé',
            'Macapá',
            'Maceió',
            'Manacapuru',
            'Manaus',
            'Manicoré',
            'Marabá',
            'Maracaju',
            'Marília',
            'Maringá',
            'Maués',
            'Mineiros',
            'Miracema',
            'Montes Claros',
            'Morrinhos',
            'Mossoró',
            'Muriaé',
            'Nanuque',
            'Natal',
            'Natal',
            'Niquelândia',
            'Niterói',
            'Nova Cruz',
            'Nova Friburgo',
            'Nova Lima',
            'Nova Viçosa',
            'Novo Airão',
            'Novo Hamburgo',
            'Novo Horizonte',
            'Óbidos',
            'Olinda',
            'Oriximiná',
            'Osório',
            'Ourinhos',
            'Palmas',
            'Palmas',
            'Palmeira dos Índios',
            'Paracatu',
            'Paracuru',
            'Paragominas',
            'Paranaguá',
            'Paranaíba',
            'Parintins',
            'Parnaíba',
            'Passo Fundo',
            'Passos',
            'Patos',
            'Paulo Afonso',
            'Pedreiras',
            'Pelotas',
            'Penápolis',
            'Penedo',
            'Petrolina',
            'Petrópolis',
            'Picos',
            'Pimenta Bueno',
            'Pindamonhangaba',
            'Pinheiro',
            'Piracicaba',
            'Piraçununga',
            'Pirapora',
            'Pires do Rio',
            'Piripiri',
            'Poços de Caldas',
            'Ponta Grossa',
            'Ponta Porã',
            'Ponte Nova',
            'Pontes e Lacerda',
            'Portel',
            'Porto Alegre',
            'Porto Nacional',
            'Pôrto Seguro',
            'Pôrto União',
            'Pôrto Velho',
            'Pouso Alegre',
            'Presidente Dutra',
            'Presidente Prudente',
            'Príncipe da Beira',
            'Quaraí',
            'Quixadá',
            'Recife',
            'Registro',
            'Remanso',
            'Ribeirão Prêto',
            'Rio Branco',
            'Rio Claro',
            'Rio de Janeiro',
            'Rio Grande',
            'Rio Largo',
            'Rio Negro',
            'Rio Verde',
            'Rolim de Moura',
            'Rondonópolis',
            'Rosário',
            'Rosário do Sul',
            'Russas',
            'Salgueiro',
            'Salinópolis',
            'Salvador',
            'Santa Cruz',
            'Santa Cruz Cabrália',
            'Santa Cruz do Sul',
            'Santa Inês',
            'Santa Maria',
            'Santa Maria da Vitória',
            'Santa Rosa',
            'Santa Vitória do Palmar',
            'Santana',
            'Santana do Livramento',
            'Santarém',
            'Santo André',
            'Santo Ângelo',
            'Santos',
            'São Borja',
            'São Carlos',
            'São Francisco do Sul',
            'São Gabriel',
            'São Gabriel da Cachoeira',
            'São João da Boa Vista',
            'São João del Rei',
            'São José de Ribamar',
            'São José do Rio Prêto',
            'São José dos Campos',
            'São José dos Pinhais',
            'São Lourenço do Sul',
            'São Luís',
            'São Luís Gonzaga',
            'São Mateus',
            'São Paulo',
            'Sena Madureira',
            'Senhor do Bonfim',
            'Serrinha',
            'Sete Lagoas',
            'Sinop',
            'Sobral',
            'Sorocaba',
            'Tatuí',
            'Tauá',
            'Taubaté',
            'Tefé',
            'Telêmaco Borba',
            'Teófilo Otoni',
            'Teresina',
            'Timbaúba',
            'Timon',
            'Tocantinópolis',
            'Tonantins',
            'Três Lagoas',
            'Trindade',
            'Tubarão',
            'Tucano',
            'Tucuruí',
            'Tupã',
            'Ubá',
            'Ubaitaba',
            'Uberaba',
            'Uberlândia',
            'Uruguaiana',
            'Vacaria',
            'Valença',
            'Várzea Grande',
            'Viana',
            'Vila Velha',
            'Vila Velha',
            'Vilhena',
            'Viseu',
            'Vitória',
            'Vitória da Conquista',
            'Volta Redonda',
            'Xinguara',
            'Xique-Xique',


        ]
    },
    {
        "id": 0,
        "departamento": "Amazonas",
        "ciudades": [
            "Leticia",
            "Puerto Nari\u00f1o"
        ]
    },
    {
        "id": 1,
        "departamento": "Antioquia",
        "ciudades": [
            "Abejorral",
            "Abriaqu\u00ed",
            "Alejandr\u00eda",
            "Amag\u00e1",
            "Amalfi",
            "Andes",
            "Angel\u00f3polis",
            "Angostura",
            "Anor\u00ed",
            "Anz\u00e1",
            "Apartad\u00f3",
            "Arboletes",
            "Argelia",
            "Armenia",
            "Barbosa",
            "Bello",
            "Belmira",
            "Betania",
            "Betulia",
            "Brice\u00f1o",
            "Buritic\u00e1",
            "C\u00e1ceres",
            "Caicedo",
            "Caldas",
            "Campamento",
            "Ca\u00f1asgordas",
            "Caracol\u00ed",
            "Caramanta",
            "Carepa",
            "Carolina del Pr\u00edncipe",
            "Caucasia",
            "Chigorod\u00f3",
            "Cisneros",
            "Ciudad Bol\u00edvar",
            "Cocorn\u00e1",
            "Concepci\u00f3n",
            "Concordia",
            "Copacabana",
            "Dabeiba",
            "Donmat\u00edas",
            "Eb\u00e9jico",
            "El Bagre",
            "El Carmen de Viboral",
            "El Pe\u00f1ol",
            "El Retiro",
            "El Santuario",
            "Entrerr\u00edos",
            "Envigado",
            "Fredonia",
            "Frontino",
            "Giraldo",
            "Girardota",
            "G\u00f3mez Plata",
            "Granada",
            "Guadalupe",
            "Guarne",
            "Guatap\u00e9",
            "Heliconia",
            "Hispania",
            "Itag\u00fc\u00ed",
            "Ituango",
            "Jard\u00edn",
            "Jeric\u00f3",
            "La Ceja",
            "La Estrella",
            "La Pintada",
            "La Uni\u00f3n",
            "Liborina",
            "Maceo",
            "Marinilla",
            "Medell\u00edn",
            "Montebello",
            "Murind\u00f3",
            "Mutat\u00e1",
            "Nari\u00f1o",
            "Nech\u00ed",
            "Necocl\u00ed",
            "Olaya",
            "Peque",
            "Pueblorrico",
            "Puerto Berr\u00edo",
            "Puerto Nare",
            "Puerto Triunfo",
            "Remedios",
            "Rionegro",
            "Sabanalarga",
            "Sabaneta",
            "Salgar",
            "San Andr\u00e9s de Cuerquia",
            "San Carlos",
            "San Francisco",
            "San Jer\u00f3nimo",
            "San Jos\u00e9 de la Monta\u00f1a",
            "San Juan de Urab\u00e1",
            "San Luis",
            "San Pedro de Urab\u00e1",
            "San Pedro de los Milagros",
            "San Rafael",
            "San Roque",
            "San Vicente",
            "Santa B\u00e1rbara",
            "Santa Fe de Antioquia",
            "Santa Rosa de Osos",
            "Santo Domingo",
            "Segovia",
            "Sons\u00f3n",
            "Sopetr\u00e1n",
            "T\u00e1mesis",
            "Taraz\u00e1",
            "Tarso",
            "Titirib\u00ed",
            "Toledo",
            "Turbo",
            "Uramita",
            "Urrao",
            "Valdivia",
            "Valpara\u00edso",
            "Vegach\u00ed",
            "Venecia",
            "Vig\u00eda del Fuerte",
            "Yal\u00ed",
            "Yarumal",
            "Yolomb\u00f3",
            "Yond\u00f3",
            "Zaragoza"
        ]
    },
    {
        "id": 2,
        "departamento": "Arauca",
        "ciudades": [
            "Arauca",
            "Arauquita",
            "Cravo Norte",
            "Fortul",
            "Puerto Rond\u00f3n",
            "Saravena",
            "Tame"
        ]
    },
    {
        "id": 3,
        "departamento": "Atl\u00e1ntico",
        "ciudades": [
            "Baranoa",
            "Barranquilla",
            "Campo de la Cruz",
            "Candelaria",
            "Galapa",
            "Juan de Acosta",
            "Luruaco",
            "Malambo",
            "Manat\u00ed",
            "Palmar de Varela",
            "Pioj\u00f3",
            "Polonuevo",
            "Ponedera",
            "Puerto Colombia",
            "Repel\u00f3n",
            "Sabanagrande",
            "Sabanalarga",
            "Santa Luc\u00eda",
            "Santo Tom\u00e1s",
            "Soledad",
            "Su\u00e1n",
            "Tubar\u00e1",
            "Usiacur\u00ed"
        ]
    },
    {
        "id": 4,
        "departamento": "Bol\u00edvar",
        "ciudades": [
            "Ach\u00ed",
            "Altos del Rosario",
            "Arenal",
            "Arjona",
            "Arroyohondo",
            "Barranco de Loba",
            "Brazuelo de Papayal",
            "Calamar",
            "Cantagallo",
            "Cartagena de Indias",
            "Cicuco",
            "Clemencia",
            "C\u00f3rdoba",
            "El Carmen de Bol\u00edvar",
            "El Guamo",
            "El Pe\u00f1\u00f3n",
            "Hatillo de Loba",
            "Magangu\u00e9",
            "Mahates",
            "Margarita",
            "Mar\u00eda la Baja",
            "Momp\u00f3s",
            "Montecristo",
            "Morales",
            "Noros\u00ed",
            "Pinillos",
            "Regidor",
            "R\u00edo Viejo",
            "San Crist\u00f3bal",
            "San Estanislao",
            "San Fernando",
            "San Jacinto del Cauca",
            "San Jacinto",
            "San Juan Nepomuceno",
            "San Mart\u00edn de Loba",
            "San Pablo",
            "Santa Catalina",
            "Santa Rosa",
            "Santa Rosa del Sur",
            "Simit\u00ed",
            "Soplaviento",
            "Talaigua Nuevo",
            "Tiquisio",
            "Turbaco",
            "Turban\u00e1",
            "Villanueva",
            "Zambrano"
        ]
    },
    {
        "id": 5,
        "departamento": "Boyac\u00e1",
        "ciudades": [
            "Almeida",
            "Aquitania",
            "Arcabuco",
            "Bel\u00e9n",
            "Berbeo",
            "Bet\u00e9itiva",
            "Boavita",
            "Boyac\u00e1",
            "Brice\u00f1o",
            "Buenavista",
            "Busbanz\u00e1",
            "Caldas",
            "Campohermoso",
            "Cerinza",
            "Chinavita",
            "Chiquinquir\u00e1",
            "Ch\u00edquiza",
            "Chiscas",
            "Chita",
            "Chitaraque",
            "Chivat\u00e1",
            "Chivor",
            "Ci\u00e9nega",
            "C\u00f3mbita",
            "Coper",
            "Corrales",
            "Covarach\u00eda",
            "Cubar\u00e1",
            "Cucaita",
            "Cu\u00edtiva",
            "Duitama",
            "El Cocuy",
            "El Espino",
            "Firavitoba",
            "Floresta",
            "Gachantiv\u00e1",
            "G\u00e1meza",
            "Garagoa",
            "Guacamayas",
            "Guateque",
            "Guayat\u00e1",
            "G\u00fcic\u00e1n",
            "Iza",
            "Jenesano",
            "Jeric\u00f3",
            "La Capilla",
            "La Uvita",
            "La Victoria",
            "Labranzagrande",
            "Macanal",
            "Marip\u00ed",
            "Miraflores",
            "Mongua",
            "Mongu\u00ed",
            "Moniquir\u00e1",
            "Motavita",
            "Muzo",
            "Nobsa",
            "Nuevo Col\u00f3n",
            "Oicat\u00e1",
            "Otanche",
            "Pachavita",
            "P\u00e1ez",
            "Paipa",
            "Pajarito",
            "Panqueba",
            "Pauna",
            "Paya",
            "Paz del R\u00edo",
            "Pesca",
            "Pisba",
            "Puerto Boyac\u00e1",
            "Qu\u00edpama",
            "Ramiriqu\u00ed",
            "R\u00e1quira",
            "Rond\u00f3n",
            "Saboy\u00e1",
            "S\u00e1chica",
            "Samac\u00e1",
            "San Eduardo",
            "San Jos\u00e9 de Pare",
            "San Luis de Gaceno",
            "San Mateo",
            "San Miguel de Sema",
            "San Pablo de Borbur",
            "Santa Mar\u00eda",
            "Santa Rosa de Viterbo",
            "Santa Sof\u00eda",
            "Santana",
            "Sativanorte",
            "Sativasur",
            "Siachoque",
            "Soat\u00e1",
            "Socha",
            "Socot\u00e1",
            "Sogamoso",
            "Somondoco",
            "Sora",
            "Sorac\u00e1",
            "Sotaquir\u00e1",
            "Susac\u00f3n",
            "Sutamarch\u00e1n",
            "Sutatenza",
            "Tasco",
            "Tenza",
            "Tiban\u00e1",
            "Tibasosa",
            "Tinjac\u00e1",
            "Tipacoque",
            "Toca",
            "Tog\u00fc\u00ed",
            "T\u00f3paga",
            "Tota",
            "Tunja",
            "Tunungu\u00e1",
            "Turmequ\u00e9",
            "Tuta",
            "Tutaz\u00e1",
            "\u00dambita",
            "Ventaquemada",
            "Villa de Leyva",
            "Viracach\u00e1",
            "Zetaquira"
        ]
    },
    {
        "id": 6,
        "departamento": "Caldas",
        "ciudades": [
            "Aguadas",
            "Anserma",
            "Aranzazu",
            "Belalc\u00e1zar",
            "Chinchin\u00e1",
            "Filadelfia",
            "La Dorada",
            "La Merced",
            "Manizales",
            "Manzanares",
            "Marmato",
            "Marquetalia",
            "Marulanda",
            "Neira",
            "Norcasia",
            "P\u00e1cora",
            "Palestina",
            "Pensilvania",
            "Riosucio",
            "Risaralda",
            "Salamina",
            "Saman\u00e1",
            "San Jos\u00e9",
            "Sup\u00eda",
            "Victoria",
            "Villamar\u00eda",
            "Viterbo"
        ]
    },
    {
        "id": 7,
        "departamento": "Caquet\u00e1",
        "ciudades": [
            "Albania",
            "Bel\u00e9n de los Andaqu\u00edes",
            "Cartagena del Chair\u00e1",
            "Curillo",
            "El Doncello",
            "El Paujil",
            "Florencia",
            "La Monta\u00f1ita",
            "Mil\u00e1n",
            "Morelia",
            "Puerto Rico",
            "San Jos\u00e9 del Fragua",
            "San Vicente del Cagu\u00e1n",
            "Solano",
            "Solita",
            "Valpara\u00edso"
        ]
    },
    {
        "id": 8,
        "departamento": "Casanare",
        "ciudades": [
            "Aguazul",
            "Ch\u00e1meza",
            "Hato Corozal",
            "La Salina",
            "Man\u00ed",
            "Monterrey",
            "Nunch\u00eda",
            "Orocu\u00e9",
            "Paz de Ariporo",
            "Pore",
            "Recetor",
            "Sabanalarga",
            "S\u00e1cama",
            "San Luis de Palenque",
            "T\u00e1mara",
            "Tauramena",
            "Trinidad",
            "Villanueva",
            "Yopal"
        ]
    },
    {
        "id": 9,
        "departamento": "Cauca",
        "ciudades": [
            "Almaguer",
            "Argelia",
            "Balboa",
            "Bol\u00edvar",
            "Buenos Aires",
            "Cajib\u00edo",
            "Caldono",
            "Caloto",
            "Corinto",
            "El Tambo",
            "Florencia",
            "Guachen\u00e9",
            "Guap\u00ed",
            "Inz\u00e1",
            "Jambal\u00f3",
            "La Sierra",
            "La Vega",
            "L\u00f3pez de Micay",
            "Mercaderes",
            "Miranda",
            "Morales",
            "Padilla",
            "P\u00e1ez",
            "Pat\u00eda",
            "Piamonte",
            "Piendam\u00f3",
            "Popay\u00e1n",
            "Puerto Tejada",
            "Purac\u00e9",
            "Rosas",
            "San Sebasti\u00e1n",
            "Santa Rosa",
            "Santander de Quilichao",
            "Silvia",
            "Sotar\u00e1",
            "Su\u00e1rez",
            "Sucre",
            "Timb\u00edo",
            "Timbiqu\u00ed",
            "Torib\u00edo",
            "Totor\u00f3",
            "Villa Rica"
        ]
    },
    {
        "id": 10,
        "departamento": "Cesar",
        "ciudades": [
            "Aguachica",
            "Agust\u00edn Codazzi",
            "Astrea",
            "Becerril",
            "Bosconia",
            "Chimichagua",
            "Chiriguan\u00e1",
            "Curuman\u00ed",
            "El Copey",
            "El Paso",
            "Gamarra",
            "Gonz\u00e1lez",
            "La Gloria (Cesar)",
            "La Jagua de Ibirico",
            "La Paz",
            "Manaure Balc\u00f3n del Cesar",
            "Pailitas",
            "Pelaya",
            "Pueblo Bello",
            "R\u00edo de Oro",
            "San Alberto",
            "San Diego",
            "San Mart\u00edn",
            "Tamalameque",
            "Valledupar"
        ]
    },
    {
        "id": 11,
        "departamento": "Choc\u00f3",
        "ciudades": [
            "Acand\u00ed",
            "Alto Baud\u00f3",
            "Bagad\u00f3",
            "Bah\u00eda Solano",
            "Bajo Baud\u00f3",
            "Bojay\u00e1",
            "Cant\u00f3n de San Pablo",
            "C\u00e9rtegui",
            "Condoto",
            "El Atrato",
            "El Carmen de Atrato",
            "El Carmen del Dari\u00e9n",
            "Istmina",
            "Jurad\u00f3",
            "Litoral de San Juan",
            "Llor\u00f3",
            "Medio Atrato",
            "Medio Baud\u00f3",
            "Medio San Juan",
            "N\u00f3vita",
            "Nuqu\u00ed",
            "Quibd\u00f3",
            "R\u00edo Ir\u00f3",
            "R\u00edo Quito",
            "Riosucio",
            "San Jos\u00e9 del Palmar",
            "Sip\u00ed",
            "Tad\u00f3",
            "Uni\u00f3n Panamericana",
            "Ungu\u00eda"
        ]
    },
    {
        "id": 12,
        "departamento": "Cundinamarca",
        "ciudades": [
            "Agua de Dios",
            "Alb\u00e1n",
            "Anapoima",
            "Anolaima",
            "Apulo",
            "Arbel\u00e1ez",
            "Beltr\u00e1n",
            "Bituima",
            "Bogot\u00e1",
            "Bojac\u00e1",
            "Cabrera",
            "Cachipay",
            "Cajic\u00e1",
            "Caparrap\u00ed",
            "C\u00e1queza",
            "Carmen de Carupa",
            "Chaguan\u00ed",
            "Ch\u00eda",
            "Chipaque",
            "Choach\u00ed",
            "Chocont\u00e1",
            "Cogua",
            "Cota",
            "Cucunub\u00e1",
            "El Colegio",
            "El Pe\u00f1\u00f3n",
            "El Rosal",
            "Facatativ\u00e1",
            "F\u00f3meque",
            "Fosca",
            "Funza",
            "F\u00faquene",
            "Fusagasug\u00e1",
            "Gachal\u00e1",
            "Gachancip\u00e1",
            "Gachet\u00e1",
            "Gama",
            "Girardot",
            "Granada",
            "Guachet\u00e1",
            "Guaduas",
            "Guasca",
            "Guataqu\u00ed",
            "Guatavita",
            "Guayabal de S\u00edquima",
            "Guayabetal",
            "Guti\u00e9rrez",
            "Jerusal\u00e9n",
            "Jun\u00edn",
            "La Calera",
            "La Mesa",
            "La Palma",
            "La Pe\u00f1a",
            "La Vega",
            "Lenguazaque",
            "Machet\u00e1",
            "Madrid",
            "Manta",
            "Medina",
            "Mosquera",
            "Nari\u00f1o",
            "Nemoc\u00f3n",
            "Nilo",
            "Nimaima",
            "Nocaima",
            "Pacho",
            "Paime",
            "Pandi",
            "Paratebueno",
            "Pasca",
            "Puerto Salgar",
            "Pul\u00ed",
            "Quebradanegra",
            "Quetame",
            "Quipile",
            "Ricaurte",
            "San Antonio del Tequendama",
            "San Bernardo",
            "San Cayetano",
            "San Francisco",
            "San Juan de Rioseco",
            "Sasaima",
            "Sesquil\u00e9",
            "Sibat\u00e9",
            "Silvania",
            "Simijaca",
            "Soacha",
            "Sop\u00f3",
            "Subachoque",
            "Suesca",
            "Supat\u00e1",
            "Susa",
            "Sutatausa",
            "Tabio",
            "Tausa",
            "Tena",
            "Tenjo",
            "Tibacuy",
            "Tibirita",
            "Tocaima",
            "Tocancip\u00e1",
            "Topaip\u00ed",
            "Ubal\u00e1",
            "Ubaque",
            "Ubat\u00e9",
            "Une",
            "\u00datica",
            "Venecia",
            "Vergara",
            "Vian\u00ed",
            "Villag\u00f3mez",
            "Villapinz\u00f3n",
            "Villeta",
            "Viot\u00e1",
            "Yacop\u00ed",
            "Zipac\u00f3n",
            "Zipaquir\u00e1"
        ]
    },
    {
        "id": 13,
        "departamento": "C\u00f3rdoba",
        "ciudades": [
            "Ayapel",
            "Buenavista",
            "Canalete",
            "Ceret\u00e9",
            "Chim\u00e1",
            "Chin\u00fa",
            "Ci\u00e9naga de Oro",
            "Cotorra",
            "La Apartada",
            "Lorica",
            "Los C\u00f3rdobas",
            "Momil",
            "Montel\u00edbano",
            "Monter\u00eda",
            "Mo\u00f1itos",
            "Planeta Rica",
            "Pueblo Nuevo",
            "Puerto Escondido",
            "Puerto Libertador",
            "Pur\u00edsima",
            "Sahag\u00fan",
            "San Andr\u00e9s de Sotavento",
            "San Antero",
            "San Bernardo del Viento",
            "San Carlos",
            "San Jos\u00e9 de Ur\u00e9",
            "San Pelayo",
            "Tierralta",
            "Tuch\u00edn",
            "Valencia"
        ]
    },
    {
        "id": 14,
        "departamento": "Guain\u00eda",
        "ciudades": [
            "In\u00edrida"
        ]
    },
    {
        "id": 15,
        "departamento": "Guaviare",
        "ciudades": [
            "Calamar",
            "El Retorno",
            "Miraflores",
            "San Jos\u00e9 del Guaviare"
        ]
    },
    {
        "id": 16,
        "departamento": "Huila",
        "ciudades": [
            "Acevedo",
            "Agrado",
            "Aipe",
            "Algeciras",
            "Altamira",
            "Baraya",
            "Campoalegre",
            "Colombia",
            "El Pital",
            "El\u00edas",
            "Garz\u00f3n",
            "Gigante",
            "Guadalupe",
            "Hobo",
            "\u00cdquira",
            "Isnos",
            "La Argentina",
            "La Plata",
            "N\u00e1taga",
            "Neiva",
            "Oporapa",
            "Paicol",
            "Palermo",
            "Palestina",
            "Pitalito",
            "Rivera",
            "Saladoblanco",
            "San Agust\u00edn",
            "Santa Mar\u00eda",
            "Suaza",
            "Tarqui",
            "Tello",
            "Teruel",
            "Tesalia",
            "Timan\u00e1",
            "Villavieja",
            "Yaguar\u00e1"
        ]
    },
    {
        "id": 17,
        "departamento": "La Guajira",
        "ciudades": [
            "Albania",
            "Barrancas",
            "Dibulla",
            "Distracci\u00f3n",
            "El Molino",
            "Fonseca",
            "Hatonuevo",
            "La Jagua del Pilar",
            "Maicao",
            "Manaure",
            "Riohacha",
            "San Juan del Cesar",
            "Uribia",
            "Urumita",
            "Villanueva"
        ]
    },
    {
        "id": 18,
        "departamento": "Magdalena",
        "ciudades": [
            "Algarrobo",
            "Aracataca",
            "Ariguan\u00ed",
            "Cerro de San Antonio",
            "Chibolo",
            "Chibolo",
            "Ci\u00e9naga",
            "Concordia",
            "El Banco",
            "El Pi\u00f1\u00f3n",
            "El Ret\u00e9n",
            "Fundaci\u00f3n",
            "Guamal",
            "Nueva Granada",
            "Pedraza",
            "Piji\u00f1o del Carmen",
            "Pivijay",
            "Plato",
            "Pueblo Viejo",
            "Remolino",
            "Sabanas de San \u00c1ngel",
            "Salamina",
            "San Sebasti\u00e1n de Buenavista",
            "San Zen\u00f3n",
            "Santa Ana",
            "Santa B\u00e1rbara de Pinto",
            "Santa Marta",
            "Sitionuevo",
            "Tenerife",
            "Zapay\u00e1n",
            "Zona Bananera"
        ]
    },
    {
        "id": 19,
        "departamento": "Meta",
        "ciudades": [
            "Acac\u00edas",
            "Barranca de Up\u00eda",
            "Cabuyaro",
            "Castilla la Nueva",
            "Cubarral",
            "Cumaral",
            "El Calvario",
            "El Castillo",
            "El Dorado",
            "Fuente de Oro",
            "Granada",
            "Guamal",
            "La Macarena",
            "La Uribe",
            "Lejan\u00edas",
            "Mapirip\u00e1n",
            "Mesetas",
            "Puerto Concordia",
            "Puerto Gait\u00e1n",
            "Puerto Lleras",
            "Puerto L\u00f3pez",
            "Puerto Rico",
            "Restrepo",
            "San Carlos de Guaroa",
            "San Juan de Arama",
            "San Juanito",
            "San Mart\u00edn",
            "Villavicencio",
            "Vista Hermosa"
        ]
    },
    {
        "id": 20,
        "departamento": "Nari\u00f1o",
        "ciudades": [
            "Aldana",
            "Ancuy\u00e1",
            "Arboleda",
            "Barbacoas",
            "Bel\u00e9n",
            "Buesaco",
            "Chachag\u00fc\u00ed",
            "Col\u00f3n",
            "Consac\u00e1",
            "Contadero",
            "C\u00f3rdoba",
            "Cuaspud",
            "Cumbal",
            "Cumbitara",
            "El Charco",
            "El Pe\u00f1ol",
            "El Rosario",
            "El Tabl\u00f3n",
            "El Tambo",
            "Francisco Pizarro",
            "Funes",
            "Guachucal",
            "Guaitarilla",
            "Gualmat\u00e1n",
            "Iles",
            "Imu\u00e9s",
            "Ipiales",
            "La Cruz",
            "La Florida",
            "La Llanada",
            "La Tola",
            "La Uni\u00f3n",
            "Leiva",
            "Linares",
            "Los Andes",
            "Mag\u00fc\u00ed Pay\u00e1n",
            "Mallama",
            "Mosquera",
            "Nari\u00f1o",
            "Olaya Herrera",
            "Ospina",
            "Pasto",
            "Policarpa",
            "Potos\u00ed",
            "Providencia",
            "Puerres",
            "Pupiales",
            "Ricaurte",
            "Roberto Pay\u00e1n",
            "Samaniego",
            "San Bernardo",
            "San Jos\u00e9 de Alb\u00e1n",
            "San Lorenzo",
            "San Pablo",
            "San Pedro de Cartago",
            "Sandon\u00e1",
            "Santa B\u00e1rbara",
            "Santacruz",
            "Sapuyes",
            "Taminango",
            "Tangua",
            "Tumaco",
            "T\u00faquerres",
            "Yacuanquer"
        ]
    },
    {
        "id": 21,
        "departamento": "Norte de Santander",
        "ciudades": [
            "\u00c1brego",
            "Arboledas",
            "Bochalema",
            "Bucarasica",
            "C\u00e1chira",
            "C\u00e1cota",
            "Chin\u00e1cota",
            "Chitag\u00e1",
            "Convenci\u00f3n",
            "C\u00facuta",
            "Cucutilla",
            "Duran\u00eda",
            "El Carmen",
            "El Tarra",
            "El Zulia",
            "Gramalote",
            "Hacar\u00ed",
            "Herr\u00e1n",
            "La Esperanza",
            "La Playa de Bel\u00e9n",
            "Labateca",
            "Los Patios",
            "Lourdes",
            "Mutiscua",
            "Oca\u00f1a",
            "Pamplona",
            "Pamplonita",
            "Puerto Santander",
            "Ragonvalia",
            "Salazar de Las Palmas",
            "San Calixto",
            "San Cayetano",
            "Santiago",
            "Santo Domingo de Silos",
            "Sardinata",
            "Teorama",
            "Tib\u00fa",
            "Toledo",
            "Villa Caro",
            "Villa del Rosario"
        ]
    },
    {
        "id": 22,
        "departamento": "Putumayo",
        "ciudades": [
            "Col\u00f3n",
            "Mocoa",
            "Orito",
            "Puerto As\u00eds",
            "Puerto Caicedo",
            "Puerto Guzm\u00e1n",
            "Puerto Legu\u00edzamo",
            "San Francisco",
            "San Miguel",
            "Santiago",
            "Sibundoy",
            "Valle del Guamuez",
            "Villagarz\u00f3n"
        ]
    },
    {
        "id": 23,
        "departamento": "Quind\u00edo",
        "ciudades": [
            "Armenia",
            "Buenavista",
            "Calarc\u00e1",
            "Circasia",
            "C\u00f3rdoba",
            "Filandia",
            "G\u00e9nova",
            "La Tebaida",
            "Montenegro",
            "Pijao",
            "Quimbaya",
            "Salento"
        ]
    },
    {
        "id": 24,
        "departamento": "Risaralda",
        "ciudades": [
            "Ap\u00eda",
            "Balboa",
            "Bel\u00e9n de Umbr\u00eda",
            "Dosquebradas",
            "Gu\u00e1tica",
            "La Celia",
            "La Virginia",
            "Marsella",
            "Mistrat\u00f3",
            "Pereira",
            "Pueblo Rico",
            "Quinch\u00eda",
            "Santa Rosa de Cabal",
            "Santuario"
        ]
    },
    {
        "id": 25,
        "departamento": "San Andr\u00e9s y Providencia",
        "ciudades": [
            "Providencia y Santa Catalina Islas",
            "San Andr\u00e9s"
        ]
    },
    {
        "id": 26,
        "departamento": "Santander",
        "ciudades": [
            "Aguada",
            "Albania",
            "Aratoca",
            "Barbosa",
            "Barichara",
            "Barrancabermeja",
            "Betulia",
            "Bol\u00edvar",
            "Bucaramanga",
            "Cabrera",
            "California",
            "Capitanejo",
            "Carcas\u00ed",
            "Cepit\u00e1",
            "Cerrito",
            "Charal\u00e1",
            "Charta",
            "Chima",
            "Chipat\u00e1",
            "Cimitarra",
            "Concepci\u00f3n",
            "Confines",
            "Contrataci\u00f3n",
            "Coromoro",
            "Curit\u00ed",
            "El Carmen de Chucur\u00ed",
            "El Guacamayo",
            "El Pe\u00f1\u00f3n",
            "El Play\u00f3n",
            "El Socorro",
            "Encino",
            "Enciso",
            "Flori\u00e1n",
            "Floridablanca",
            "Gal\u00e1n",
            "G\u00e1mbita",
            "Gir\u00f3n",
            "Guaca",
            "Guadalupe",
            "Guapot\u00e1",
            "Guavat\u00e1",
            "G\u00fcepsa",
            "Hato",
            "Jes\u00fas Mar\u00eda",
            "Jord\u00e1n",
            "La Belleza",
            "La Paz",
            "Land\u00e1zuri",
            "Lebrija",
            "Los Santos",
            "Macaravita",
            "M\u00e1laga",
            "Matanza",
            "Mogotes",
            "Molagavita",
            "Ocamonte",
            "Oiba",
            "Onzaga",
            "Palmar",
            "Palmas del Socorro",
            "P\u00e1ramo",
            "Piedecuesta",
            "Pinchote",
            "Puente Nacional",
            "Puerto Parra",
            "Puerto Wilches",
            "Rionegro",
            "Sabana de Torres",
            "San Andr\u00e9s",
            "San Benito",
            "San Gil",
            "San Joaqu\u00edn",
            "San Jos\u00e9 de Miranda",
            "San Miguel",
            "San Vicente de Chucur\u00ed",
            "Santa B\u00e1rbara",
            "Santa Helena del Op\u00f3n",
            "Simacota",
            "Suaita",
            "Sucre",
            "Surat\u00e1",
            "Tona",
            "Valle de San Jos\u00e9",
            "V\u00e9lez",
            "Vetas",
            "Villanueva",
            "Zapatoca"
        ]
    },
    {
        "id": 27,
        "departamento": "Sucre",
        "ciudades": [
            "Buenavista",
            "Caimito",
            "Chal\u00e1n",
            "Colos\u00f3",
            "Corozal",
            "Cove\u00f1as",
            "El Roble",
            "Galeras",
            "Guaranda",
            "La Uni\u00f3n",
            "Los Palmitos",
            "Majagual",
            "Morroa",
            "Ovejas",
            "Sampu\u00e9s",
            "San Antonio de Palmito",
            "San Benito Abad",
            "San Juan de Betulia",
            "San Marcos",
            "San Onofre",
            "San Pedro",
            "Sinc\u00e9",
            "Sincelejo",
            "Sucre",
            "Tol\u00fa",
            "Tol\u00fa Viejo"
        ]
    },
    {
        "id": 28,
        "departamento": "Tolima",
        "ciudades": [
            "Alpujarra",
            "Alvarado",
            "Ambalema",
            "Anzo\u00e1tegui",
            "Armero",
            "Ataco",
            "Cajamarca",
            "Carmen de Apical\u00e1",
            "Casabianca",
            "Chaparral",
            "Coello",
            "Coyaima",
            "Cunday",
            "Dolores",
            "El Espinal",
            "Fal\u00e1n",
            "Flandes",
            "Fresno",
            "Guamo",
            "Herveo",
            "Honda",
            "Ibagu\u00e9",
            "Icononzo",
            "L\u00e9rida",
            "L\u00edbano",
            "Mariquita",
            "Melgar",
            "Murillo",
            "Natagaima",
            "Ortega",
            "Palocabildo",
            "Piedras",
            "Planadas",
            "Prado",
            "Purificaci\u00f3n",
            "Rioblanco",
            "Roncesvalles",
            "Rovira",
            "Salda\u00f1a",
            "San Antonio",
            "San Luis",
            "Santa Isabel",
            "Su\u00e1rez",
            "Valle de San Juan",
            "Venadillo",
            "Villahermosa",
            "Villarrica"
        ]
    },
    {
        "id": 29,
        "departamento": "Valle del Cauca",
        "ciudades": [
            "Alcal\u00e1",
            "Andaluc\u00eda",
            "Ansermanuevo",
            "Argelia",
            "Bol\u00edvar",
            "Buenaventura",
            "Buga",
            "Bugalagrande",
            "Caicedonia",
            "Cali",
            "Calima",
            "Candelaria",
            "Cartago",
            "Dagua",
            "El \u00c1guila",
            "El Cairo",
            "El Cerrito",
            "El Dovio",
            "Florida",
            "Ginebra",
            "Guacar\u00ed",
            "Jamund\u00ed",
            "La Cumbre",
            "La Uni\u00f3n",
            "La Victoria",
            "Obando",
            "Palmira",
            "Pradera",
            "Restrepo",
            "Riofr\u00edo",
            "Roldanillo",
            "San Pedro",
            "Sevilla",
            "Toro",
            "Trujillo",
            "Tulu\u00e1",
            "Ulloa",
            "Versalles",
            "Vijes",
            "Yotoco",
            "Yumbo",
            "Zarzal"
        ]
    },
    {
        "id": 30,
        "departamento": "Vaup\u00e9s",
        "ciudades": [
            "Carur\u00fa",
            "Mit\u00fa",
            "Taraira"
        ]
    },
    {
        "id": 31,
        "departamento": "Vichada",
        "ciudades": [
            "Cumaribo",
            "La Primavera",
            "Puerto Carre\u00f1o",
            "Santa Rosal\u00eda"
        ]
    }

]

export default CiudadesData